# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: true
sudo: true
cache: packages




addons:
    apt:
        packages:
            - libudunits2-dev
            - libnetcdf-dev
            - netcdf-bin
            - libproj-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev


matrix:
    include:
        - os: linux
          r: release
          dist: trusty # 14.04
          env:
           - BUILD_NAME=trusty_release
           - DETAILS="old trusty"
        - os: linux
          r: release
          dist: xenial # 16.04
          env:
           - BUILD_NAME=xenial_release
           - DETAILS="release build"
        - os: osx
          r: release
          env:
           - BUILD_NAME=osx_release
           - DETAILS="release build"

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
